import { Component, OnInit } from '@angular/core';
import { SqliteService } from 'src/app/services/sqlite.service';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { IonicModule } from '@ionic/angular';
import { NavController } from '@ionic/angular';

interface StatCard {
  title: string;
  value: string | number;
  displayValue: string | number; // For animated counting
  targetValue: number; // The final value to animate to
  icon: string;
  color: string;
  prefix?: string; // For currency symbols or units
  suffix?: string; // For units
  decimals?: number; // For decimal precision
}

interface Achievement {
  name: string;
  description: string;
  icon: string;
  achieved: boolean;
}

/**
 * Represents the stats page of the application, displaying user statistics,
 * achievements, and environmental impact based on recycling data.
 */
@Component({
  selector: 'app-stats',
  templateUrl: './stats.page.html',
  styleUrls: ['./stats.page.scss'],
  standalone: true,
  imports: [CommonModule, FormsModule, IonicModule]
})
export class StatsPage implements OnInit {
  /** The name of the user. */
  userName = 'John Doe';

  /** The user's current level or title. */
  userLevel = 'Recycling Champion';

  /** The path to the user's profile image. */
  userProfileImage = 'assets/avatar-placeholder.png';

  /** The total number of bottles returned by the user. */
  totalBottles = 0;

  /** The total amount of money saved by the user through recycling. */
  totalSaved = 0;

  /** The total number of receipts generated by the user. */
  totalReceipts = 0;

  /** A list of the top stores where the user has returned bottles. */
  topStores: { name: string; count: number }[] = [];

  /** A list of stat cards displaying various statistics with animations. */
  statCards: StatCard[] = [];

  /** A list of achievements the user can unlock. */
  achievements: Achievement[] = [
    {
      name: 'First Return',
      description: 'Return your first bottle',
      icon: 'trophy',
      achieved: false
    },
    {
      name: 'Dedicated Recycler',
      description: 'Return bottles 5 days in a row',
      icon: 'calendar',
      achieved: false
    },
    {
      name: 'Century Club',
      description: 'Return 100 bottles in total',
      icon: 'trophy',
      achieved: false
    },
    {
      name: 'Eco Warrior',
      description: 'Return bottles from 10 different locations',
      icon: 'earth',
      achieved: false
    }
  ];

  /** The duration of the animation for stat updates, in milliseconds. */
  animationDuration = 1500;

  /** The number of frames for the animation. */
  animationFrames = 20;

  /** The animated display value for the total bottles returned. */
  displayBottles = 0;

  /** The animated display value for CO₂ reduction. */
  displayCO2 = '0';

  /** The animated display value for landfill reduction. */
  displayLandfill = '0';

  constructor(
    private sqliteService: SqliteService,
    private navCtrl: NavController
  ) { }

  /**
   * Lifecycle hook that is called after the component is initialized.
   * Loads the user's stats.
   */
  ngOnInit() {
    this.loadStats();
  }

  /**
   * Lifecycle hook that is called when the page is about to enter and become active.
   * Reloads the user's stats.
   */
  ionViewWillEnter() {
    this.loadStats();
  }

  /**
   * Loads the user's stats from the SQLite database and updates the UI.
   */
  loadStats() {
    const receipts = this.sqliteService.getReceipts();
    
    this.totalReceipts = receipts.length;
    
    this.totalBottles = receipts.reduce((total, receipt) => {
      const actualBottles = (receipt.bottle_count / 100) / 0.15;
      return total + actualBottles;
    }, 0);
    
    this.totalBottles = Math.round(this.totalBottles);
    this.totalSaved = receipts.reduce((total, receipt) => total + receipt.total_amount, 0);
    
    const storeMap = new Map<string, number>();
    receipts.forEach(receipt => {
      const actualBottles = Math.round((receipt.bottle_count / 100) / 0.15);
      const count = storeMap.get(receipt.store_name) || 0;
      storeMap.set(receipt.store_name, count + actualBottles);
    });
    
    this.topStores = Array.from(storeMap.entries())
      .map(([name, count]) => ({ name, count }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 3);
    
    // Create stat cards with animation values
    this.statCards = [
      {
        title: 'Total Bottles',
        value: this.totalBottles,
        displayValue: 0,
        targetValue: this.totalBottles,
        icon: 'water',
        color: 'primary'
      },
      {
        title: 'Money Saved',
        value: `€${this.totalSaved.toFixed(2)}`,
        displayValue: '€0.00',
        targetValue: this.totalSaved,
        prefix: '€',
        decimals: 2,
        icon: 'cash-outline',
        color: 'success'
      },
      {
        title: 'Receipts',
        value: this.totalReceipts,
        displayValue: 0,
        targetValue: this.totalReceipts,
        icon: 'receipt-outline',
        color: 'tertiary'
      },
      {
        title: 'CO₂ Reduced',
        value: `${(this.totalBottles * 0.08).toFixed(2)}kg`,
        displayValue: '0kg',
        targetValue: this.totalBottles * 0.08,
        suffix: 'kg',
        decimals: 2,
        icon: 'leaf-outline',
        color: 'success'
      }
    ];
    
    // Reset display values for environmental impact
    this.displayBottles = 0;
    this.displayCO2 = '0';
    this.displayLandfill = '0';
    
    // Trigger animations
    this.animateNumbers();
    
    this.updateAchievements(receipts);
  }

  /**
   * Animates the numbers on the stat cards and environmental impact values.
   */
  animateNumbers() {
    // Animate stat cards
    let currentFrame = 0;
    
    const animationInterval = setInterval(() => {
      currentFrame++;
      const progress = Math.min(currentFrame / this.animationFrames, 1);
      const easedProgress = this.easeOutQuad(progress);
      
      // Update each stat card
      this.statCards.forEach(stat => {
        if (typeof stat.targetValue === 'number') {
          const rawValue = stat.targetValue * easedProgress;
          
          if (stat.decimals) {
            // Format with decimal places
            const formattedValue = rawValue.toFixed(stat.decimals);
            stat.displayValue = `${stat.prefix || ''}${formattedValue}${stat.suffix || ''}`;
          } else {
            // Format as integer
            const formattedValue = Math.round(rawValue);
            stat.displayValue = `${stat.prefix || ''}${formattedValue}${stat.suffix || ''}`;
          }
        }
      });
      
      // Update environmental impact values
      this.displayBottles = Math.round(this.totalBottles * easedProgress);
      this.displayCO2 = (this.totalBottles * 0.08 * easedProgress).toFixed(2);
      this.displayLandfill = (this.totalBottles * 0.01 * easedProgress).toFixed(2);
      
      if (currentFrame >= this.animationFrames) {
        clearInterval(animationInterval);
        
        // Ensure we end up with exact target values
        this.statCards.forEach(stat => {
          if (typeof stat.targetValue === 'number') {
            if (stat.decimals) {
              stat.displayValue = `${stat.prefix || ''}${stat.targetValue.toFixed(stat.decimals)}${stat.suffix || ''}`;
            } else {
              stat.displayValue = `${stat.prefix || ''}${Math.round(stat.targetValue)}${stat.suffix || ''}`;
            }
          }
        });
        
        this.displayBottles = this.totalBottles;
        this.displayCO2 = (this.totalBottles * 0.08).toFixed(2);
        this.displayLandfill = (this.totalBottles * 0.01).toFixed(2);
      }
    }, this.animationDuration / this.animationFrames);
  }
  
  /**
   * Easing function for smoother animation.
   * @param t - The current progress of the animation (0 to 1).
   * @returns The eased progress value.
   */
  easeOutQuad(t: number): number {
    return t * (2 - t);
  }

  /**
   * Updates the user's achievements based on the provided receipts.
   * @param receipts - The list of receipts to evaluate.
   */
  updateAchievements(receipts: any[]) {
    this.achievements[0].achieved = receipts.length > 0;
    this.achievements[2].achieved = this.totalBottles >= 100;
    
    const uniqueLocations = new Set(receipts.map(receipt => receipt.location)).size;
    this.achievements[3].achieved = uniqueLocations >= 10;
    this.achievements[1].achieved = false;
  }

  /**
   * Navigates back to the previous page.
   */
  goBack() {
    this.navCtrl.navigateBack('/');
  }
}
